APPLY_FIXES: all
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
YAML_V8R_FILTER_REGEX_EXCLUDE: .mega-linter.yml
PYTHON_BLACK_CONFIG_FILE: .python-black
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: templates/
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: templates/
DISABLE_LINTERS:
  - REPOSITORY_DUSTILOCK
  - REPOSITORY_GIT_DIFF
  - REPOSITORY_TRIVY
  - REPOSITORY_DEVSKIM
  - REPOSITORY_CHECKOV
  - REPOSITORY_KICS
  - MARKDOWN_MARKDOWN_LINK_CHECK
DISABLE:
  - COPYPASTE
  - SPELL
