nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  # TODO - update image params when image is pushed to repo.
  repository: quay.io/ortelius/ms-compitem-crud
  #digest: 
  tag: main-v9.0.0.17-g106d15a

service:
  type: NodePort
  portName: env2app-port
  exposedPort: 8080
  targetPort: 80
  nodePort: 30080

envVars:
  DB_HOST: 192.168.10.96
  DB_PORT: 6543
  DB_NAME: postgres


resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
