Chart: chart/ms-compitem-crud
ChartNamespace: ortelius
DockerRepo: quay.io/ortelius/ms-compitem-crud
DockerSha: 786315f25117ca866266e9208e3b2932c63dcacb07aa683e4d9ad59f1b21a375
DockerTag: deploy-v10.0.0.72-g9739086
EXT: sh
GitBranch: deploy
GitCommit: '9739086'
GitRepo: ortelius/ortelius-ms-compitem-crud
GitTag: deploy
GitUrl: git@github.com:ortelius/ortelius-ms-compitem-crud.git
RE_PHYSICAL_HOSTNAME: localhost
RE_PHYSICAL_SERVER: localhost
aks:
  admin: true
  certificate: /root/.ssh/aks.pem
  cluster: cluster2-aks
  resourcegroup: cluster1-rg
application: ortelius-devops;10_0_14
builddate: Fri Jan 21 00:20:03 UTC 2022
buildid: 4789801f-9a02-437c-a762-518dbb7f4849
buildurl: https://console.cloud.google.com/cloud-build/builds/4789801f-9a02-437c-a762-518dbb7f4849?project=eighth-physics-169321
chart: chart/ms-compitem-crud
chartnamespace: ortelius
chartpublish: Y
component: ms-compitem-crud;deploy;v10_0_0_72_g9739086
dockerrepo: quay.io/ortelius/ms-compitem-crud
dockersha: 786315f25117ca866266e9208e3b2932c63dcacb07aa683e4d9ad59f1b21a375
dockertag: deploy-v10.0.0.72-g9739086
dropzone: /tmp/tdm.1495.5
environment: aks-cluster
gitcommit: '9739086'
gitrepo: ortelius/ortelius-ms-compitem-crud
gittag: deploy
giturl: git@github.com:ortelius/ortelius-ms-compitem-crud.git
image:
  pullPolicy: Always
kubectl_context: cluster2-aks-admin
server_hostname: localhost
server_name: localhost
